// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ctrlspec.Data;

#nullable disable

namespace ctrlspec.Migrations
{
    [DbContext(typeof(CtrlSpecDbContext))]
    partial class CtrlSpecDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationList", b =>
                {
                    b.Property<int?>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AppId"));

                    b.Property<string>("AgeOfApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllocatedDiskSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BacklogMinorChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BacklogProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BacklogServiceRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessDifferentiation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessNeedsAdequacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessProcessLevel1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessProcessLevel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPUTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPUTEMANUF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPUTERUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPUTERUNMarketBased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateToGHOSTSRV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateToPSMutualization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarbonIntensityRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudCompatibleArchitecture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudMigrationComplexity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudMigrationComplexitySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudMigrationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudMigrationWave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudServiceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudTargetInfrastructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confidentiality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostPerYearAWS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostPerYearAzure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Criticality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CyberSecurityScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataResidency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseManagementSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecommissioningPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecommissioningType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemandQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deployment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevOpsMaturity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiskSpaceUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dynamism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtDeliveryModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalFPStaffCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOffshoreRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalStaffCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEExternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEExternalFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEInternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEMajorChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEMinorChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTEServiceRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalComplexity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Global")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalOffshoreRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAETProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostingRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostingRateRECIncluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITDigitalReadiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITLandscape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITSubDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstabilityRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntDeliveryModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Integrity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalOffshoreRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalStaffCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelOfIntegration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelOfRobustness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePortability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainOSInProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainProdServersLocations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTechnologies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maintainability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintainabilityRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorChangesCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagedServicesCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturingRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxAcceptableDowntime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinorChangesCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NicheProgrammingLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonProductionServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonProductionVirtualServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfITPPerYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfMajorReleases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfMinorChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfServiceRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERATINGMODEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSObsolescence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PUERate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Package")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageCustomization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleDependencyRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemsCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionPhysicalServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionServerRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionVirtualServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPortfolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicCloudBlocker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RPO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalizationCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalizationDestiny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalizationSolutionQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalizationTCOLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalizationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadyForAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedundantApplications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regulatory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenewableEnergyRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredTTM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseTimeLatencyRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScatterView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityCompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceRequestsCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionMix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceCodeAvailability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliersDependency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuppliersDependencyRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCFKgCO2ePerYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalObsolescence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalObsolescenceRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalInfrastructureCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalServers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalStaffCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedDiskSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VirtualizationRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VirtualizationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolatilityRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebCollectCompleteness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppId");

                    b.ToTable("ApplicationLists");
                });

            modelBuilder.Entity("ctrlspec.Models.Application", b =>
                {
                    b.Property<int>("C_Id")
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Application_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serverinfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ctrlspec.Models.EmailModel", b =>
                {
                    b.Property<string>("To")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("To");

                    b.ToTable("emailModel");
                });

            modelBuilder.Entity("ctrlspec.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHasher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ResetPasswordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("login");
                });

            modelBuilder.Entity("ctrlspec.Models.ServerList", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("AWSCostPerYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AzureCostPerYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datacenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Energy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergyPUEIncluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Global")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITLandscape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsMutualized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOrphan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANUF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfApplicationsMapped")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfCPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSNormalized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSVersionNormalized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAMSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUNMarketBased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservedInstance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVCarbonIntensityRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVHostingRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVHostingRateRECIncluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVPUERate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVRenewableEnergyRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRVTCF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScatterView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerDetailedLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerMigrationCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerMigrationMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerMigrationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerOSObsolescence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerTargetInfrastructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teeshirt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAllocatedDiskSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfServerNormalized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsageHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedDiskSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Virtualized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebCollectCompleteness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("ServerLists");
                });

            modelBuilder.Entity("ctrlspec.Models.Application", b =>
                {
                    b.HasOne("ctrlspec.Models.Login", "login")
                        .WithOne("Application")
                        .HasForeignKey("ctrlspec.Models.Application", "C_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("login");
                });

            modelBuilder.Entity("ctrlspec.Models.ServerList", b =>
                {
                    b.HasOne("ApplicationList", "ApplicationLists")
                        .WithMany()
                        .HasForeignKey("AppId");

                    b.Navigation("ApplicationLists");
                });

            modelBuilder.Entity("ctrlspec.Models.Login", b =>
                {
                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
